# For production:
backend:
  name: github
  repo: ezac-gliding/ezac-website-upgrade-gatsby
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# For local dev:
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1

media_folder: static/assets
public_folder: assets

collections:
  - name: "glider"
    extension: "json"
    label: "Gliders"
    label_singular: "Glider"
    summary: "{{type}} ({{callsign}})"
    folder: "src/data/gliders"
    create: true
    slug: "{{type}}-{{manufacturer}}-{{callsign}}"
    fields:
      - {label: "Manufacturer", name: "manufacturer", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Callsign", name: "callsign", widget: "string"}
      - {label: "Blueprint", name: "blueprint", widget: "image", required: false}
      - {label: "Best Glide Ratio", name: "glide-ratio", widget: "number", required: true}
      - {label: "Wing Area (m2)", name: "wing-area", widget: "string", required: false}
      - {label: "Wing Aspect Ratio", name: "wing-aspect", widget: "string", required: false}
      - {label: "Fuselage Length (m)", name: "fuselage-length", widget: "string", required: false}
      - {label: "Empty Weight (kg)", name: "empty-weight", widget: "string", required: false}
      - {label: "Max Speed (km/h)", name: "max-speed", widget: "string", required: false}
      - {label: "Min Sink (m/s)", name: "min-sink", widget: "string", required: false}
      - {label: "Scaling (%)", name: "scale", widget: "number", default: 100, required: true}
      - {label: "Order (lower is first)", name: "order", widget: "number", default: 0, required: true}

  - name: "homepage-texts"
    extension: "json"
    label: "Homepage Texts"
    label_singular: "Homepage Text"
    summary: "{{commit_author}} - ({{title}})"
    folder: "src/data/homepage-texts"
    create: true
    slug: "{{commit_author}}-{{title}}-{{commit_date}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "text"}

  - name: "club-stories"
    extension: "json"
    label: "Club Stories"
    label_singular: "Club Story"
    summary: "{{commit_author}} - ({{title}})"
    folder: "src/data/club-stories"
    create: true
    slug: "{{commit_author}}-{{title}}-{{commit_date}}"
    fields:
      - {label: "Content", name: "content", widget: "markdown", buttons: ["heading-one", "bold"], editor_components: [], required: true}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Image shadow", name: "img-shadow", widget: "boolean", default: true, required: true}
      - {label: "Image outline (only works when shadow is true)", name: "img-outline", widget: "boolean", default: false, required: true}
      - label: "Image shadow location"
        name: "img-shadow-location"
        widget: "object"
        fields:
          - {label: "X position (px)", name: "x", default: 20, widget: "number", required: true}
          - {label: "Y position (px)", name: "y", default: 20, widget: "number", required: true}
