# For production:
backend:
  name: github
  repo: ezac-gliding/ezac-website-upgrade-gatsby
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# For local dev:
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1

media_folder: static/assets
public_folder: assets

collections:
  - name: "glider"
    extension: "json"
    label: "Gliders"
    label_singular: "Glider"
    summary: "{{type}} ({{callsign}})"
    folder: "src/data/gliders"
    create: true
    slug: "{{type}}-{{manufacturer}}-{{callsign}}"
    fields:
      - {label: "Manufacturer", name: "manufacturer", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Callsign", name: "callsign", widget: "string"}
      - {label: "Blueprint", name: "blueprint", widget: "image", required: false}
      - {label: "Best Glide Ratio", name: "glide-ratio", widget: "number", required: true}
      - {label: "Wing Area (m2)", name: "wing-area", widget: "string", required: false}
      - {label: "Wing Aspect Ratio", name: "wing-aspect", widget: "string", required: false}
      - {label: "Fuselage Length (m)", name: "fuselage-length", widget: "string", required: false}
      - {label: "Empty Weight (kg)", name: "empty-weight", widget: "string", required: false}
      - {label: "Max Speed (km/h)", name: "max-speed", widget: "string", required: false}
      - {label: "Min Sink (m/s)", name: "min-sink", widget: "string", required: false}
      - {label: "Scaling (%)", name: "scale", widget: "number", default: 100, required: true}
      - {label: "Order (lower is first)", name: "order", widget: "number", default: 0, required: true}

  - name: "homepage-texts"
    extension: "json"
    label: "Homepage Texts"
    label_singular: "Homepage Text"
    summary: "{{commit_author}} - ({{title}})"
    folder: "src/data/homepage-texts"
    create: true
    slug: "{{commit_author}}-{{title}}-{{commit_date}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", required: true, default: 0}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Align", name: "align", widget: "select", options: ["left", "right"], required: true, default: "left"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "File", name: "source", widget: "image"}
          - {label: "Image shadow", name: "shadow", widget: "boolean", default: true}
          - {label: "Shadow Color", name: "color", options: ["white", "#244059", "#fff1a7", "#9DC4FF"], default: "#244059", widget: "select"}
          - {label: "Image outline (only works when shadow is true)", name: "outline", widget: "boolean", default: false}
          - {label: "Use alternate bubble type", name: "useAlternate", widget: "boolean", default: false}
          - {label: "Rotation (deg)", name: "rotation", default: 0, widget: "number"}
          - {label: "Image position x (px)", name: "imagePosX", default: 0, widget: "number"}
          - {label: "Image position y (px)", name: "imagePosY", default: 0, widget: "number"}
          - {label: "Image scale (%)", name: "imgScale", default: 140, widget: "number"}

  - name: "club-stories"
    extension: "json"
    label: "Club Stories"
    label_singular: "Club Story"
    summary: "{{commit_author}} - ({{title}})"
    folder: "src/data/club-stories"
    create: true
    slug: "{{commit_author}}-{{title}}-{{commit_date}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Content", name: "content", widget: "markdown", buttons: ["heading-one", "bold"], editor_components: [], required: true}
      - {label: "Align right", name: "alignRight", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 0, required: true}
      - {label: "Space below (px)", name: "spaceBelow", widget: "number", default: 350, required: true}
      - label: "Header ornament"
        name: "wavyPattern"
        widget: "select"
        options: ["pattern-1", "pattern-2"]
        default: "#fff1a7"
        required: false
      - label: "Text color"
        name: "textColor"
        widget: "select"
        options: ["white", "#244059", "#fff1a7", "#9DC4FF"]
        default: "white"
        required: true
      - label: "Background"
        name: "backgroundColor"
        widget: "select"
        options: ["white", "#244059", "#fff1a7", "#9DC4FF"]
        default: "#fff1a7"
        required: true
      - label: "Background Bubble"
        name: "bubble"
        widget: "object"
        fields:
          - {label: "X position (px)", name: "xOffset", default: 20, widget: "number", required: true}
          - {label: "Y position (px)", name: "yOffset", default: 20, widget: "number", required: true}
          - {label: "Rotation start (deg)", name: "rotateStart", default: 0, widget: "number"}
          - {label: "Rotation end (deg)", name: "rotateEnd", default: 0, widget: "number"}
          - {label: "Bubble Color", name: "color", options: ["white", "#244059", "#fff1a7", "#9DC4FF"], default: "#244059", widget: "select"}
          - {label: "Scale (px)", name: "scale", default: 800, widget: "number"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "File", name: "source", widget: "image"}
          - {label: "Image shadow", name: "shadow", widget: "boolean", default: true}
          - {label: "Shadow Color", name: "color", options: ["white", "#244059", "#fff1a7", "#9DC4FF"], default: "#244059", widget: "select"}
          - {label: "Image position x (px)", name: "imagePosX", default: 0, widget: "number"}
          - {label: "Image position y (px)", name: "imagePosY", default: 0, widget: "number"}
          - {label: "X position (px)", name: "xOffset", default: 0, widget: "number"}
          - {label: "Y position (px)", name: "yOffset", default: 0, widget: "number"}
          - {label: "Offset image from right", name: "fromRight", widget: "boolean", default: false}
          - {label: "Image outline (only works when shadow is true)", name: "outline", widget: "boolean", default: false}
          - {label: "Use alternate bubble type", name: "useAlternate", widget: "boolean", default: false}

  - name: "prices"
    extension: "json"
    label: "Prices"
    label_singular: "Price"
    summary: "{{commit_author}} - ({{title}})"
    folder: "src/data/prices"
    create: true
    slug: "{{commit_author}}-{{title}}-{{commit_date}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Currency", name: "currency", widget: "select", options: ["£", "€", "$"], default: "€"}
      - {label: "Color", name: "color", widget: "color", default: "#314B77"}
      - name: "features"
        label: "Features"
        widget: "list"
        fields:
          - {label: "Description", name: "description", widget: "string"}
        default: []
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Orientation", name: "orientation", widget: "number", default: 0}
